# -*- coding: utf-8 -*-
"""Toy story 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN70oLb3r55dr4iRqpB_dFhLwokyhT16
"""

from bs4 import BeautifulSoup as bs
import requests

r = requests.get('https://en.wikipedia.org/wiki/Toy_Story_3')
soup = bs(r.content)
contents = soup.prettify()

print(contents)

info_box = soup.find(class_='infobox vevent')
info_row = info_box.find_all('tr')
for row in info_row:
  print(row.prettify())